### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [MaksimBorovik/2nd#1]
весь элемент является ссылкой + соответствующая реализация поведения при наведении
![image](https://user-images.githubusercontent.com/8464662/61022872-41802700-a3b0-11e9-8361-901f27ce365c.png)
аналогично
![image](https://user-images.githubusercontent.com/8464662/61022900-62487c80-a3b0-11e9-87dd-b47ab7dec9e8.png)

конечно же этого быть не должно
![image](https://user-images.githubusercontent.com/8464662/61022904-6e343e80-a3b0-11e9-927d-93d54313c782.png)

синяя обводка мешает
![image](https://user-images.githubusercontent.com/8464662/61023089-1d711580-a3b1-11e9-95f5-ee9fc03f55a0.png)

не соответствующий отступ
![image](https://user-images.githubusercontent.com/8464662/61023139-514c3b00-a3b1-11e9-9778-5e62f9133601.png)

не соответствующий отступ, ширина
![image](https://user-images.githubusercontent.com/8464662/61023229-b43dd200-a3b1-11e9-8fb3-f5f0e6aa6242.png)

**Comment by MaksimBorovik** [comment]
Все исправил, глупые ошибки были. Всего на вечер отвлекся от проекта, переключился на Bootstrap, и потом, вернувшись уже со свежей головой, довольно быстро все ошибки и неточности решил
